select t.id,
       t.account,
       t.password,
       t.user_name,
       t.org_id,
       t.email,
       t.status,
       t.last_login_ip,
       t.last_login_time,
       t.phone,
       t.create_user,
       t.create_time,
       t.modify_user,
       t.modify_time,
       t.project_id,
       t.private_key,
       t.sex,
       t.is_activation,
       t.reasons_disable,
       t.is_admin,
       t.user_type,
       t.login_type,
       t.department_id,
       f.org_name,
       f.org_code,
       decode(f.org_type,1,'1',2,'1',3,'1',4,'2','3') org_type --企业类型：1生产企业、2代理企业、3生产及代理企业，4 配送机构
from HEC_UPO_PRJ_USER t
  left join hec_dup_fm_tender_org f on t.org_id=f.id
where t.status='1' --and t.user_type in('1','4')
 union all
 select t.opno id,
       NVL(t.opaccount,t.opno) account,
       NVL(t.pwd,'96E79218965EB72C92A549DD5A330112') password,
       t.opname user_name,
       t.unitid org_id,
       t.email email,
       to_char(t.enabled) status,
       t.lastloginip last_login_ip,
       t.activetime last_login_time,
       t.LINKTEL phone,
       '' create_user,
       t.createtime create_time,
       '' modify_user,
       null modify_time,
       '' project_id,
       '' private_key,
       null sex,
       '9' is_activation,
       '凯特用户' reasons_disable,
       '1' is_admin,
       --to_char(decode(t.optype,3,2,5,3,8,4,0,1,2,1,6,6)) user_type,--返回凯特时用
       to_char(t.optype) user_type,
       '0' login_type,
       '' department_id,
       c.compname org_name,
       c.compid org_code,
       to_char(c.comptype) org_type -- 企业类型,1国内生产企业/代理机构，2配送企业，3生产及配送企业
 from SYS_N_USERS t-- 只查询optype=5或8
 join mcs_company_info c on t.unitid=c.ent_id
 union all
 select t.opno id,
       NVL(t.opaccount,t.opno) account,
       NVL(t.pwd,'96E79218965EB72C92A549DD5A330112') password,
       t.opname user_name,
       t.unitid org_id,
       t.email email,
       to_char(t.enabled) status,
       t.lastloginip last_login_ip,
       t.activetime last_login_time,
       t.LINKTEL phone,
       '' create_user,
       t.createtime create_time,
       '' modify_user,
       null modify_time,
       '' project_id,
       '' private_key,
       null sex,
       '9' is_activation,
       '凯特用户' reasons_disable,
       '1' is_admin,
       --to_char(decode(t.optype,3,2,5,3,8,4,0,1,2,1,6,6)) user_type,--返回凯特时用
       to_char(t.optype) user_type,
       '0' login_type,
       '' department_id,
       c.hospname org_name,
       c.hospcode org_code,
       to_char(c.hospitaltype) org_type
 from SYS_N_USERS t -- 只查询optype=3
 join mcs_hospital_info c on t.unitid=c.hosp_id
 union all
  select t.opno id,
       NVL(t.opaccount,t.opno) account,
       NVL(t.pwd,'96E79218965EB72C92A549DD5A330112') password,
       t.opname user_name,
       t.unitid org_id,
       t.email email,
       to_char(t.enabled) status,
       t.lastloginip last_login_ip,
       t.activetime last_login_time,
       t.LINKTEL phone,
       '' create_user,
       t.createtime create_time,
       '' modify_user,
       null modify_time,
       '' project_id,
       '' private_key,
       null sex,
       '9' is_activation,
       '凯特用户' reasons_disable,
       '1' is_admin,
       --to_char(decode(t.optype,3,2,5,3,8,4,0,1,2,1,6,6)) user_type,--返回凯特时用
       to_char(t.optype) user_type,
       '0' login_type,
       '' department_id,
       c.regulator org_name,
       c.regcode org_code,
       to_char(c.regtype) org_type
  from SYS_N_USERS t -- 只查询医保局
  join MCS_REGULATOR_INFO c on t.unitid=c.regid
/*
  联合查询凯特企业机构和帐号信息
*/
